//! The two layers of spec §10: an append-only log, and projections over it.
//!
//! **Invariant:** `messages`, `sessions` and `projects` contain nothing that
//! cannot be regenerated by replaying `events`. `DROP` and rebuild is always a
//! valid recovery, and that is precisely what makes the fold trustworthy —
//! there is no path by which a stored status can drift from the events that
//! were actually observed. Anything that would break this invariant belongs in
//! `events`, not in a projection.
//!
//! `events` and `bodies` are the only durable truth. `bodies` is the exception
//! to the rule above because attachment bytes are *not* recoverable from the
//! log: ntfy expires attachments after 3 h but keeps messages for 12 h, so a
//! body not captured at ingest is gone for good.

use rusqlite::{Connection, Result};

/// Bumped whenever the DDL below changes. `PRAGMA user_version` is read on
/// every open, so a database written by an older build is migrated exactly
/// once rather than re-created or silently mis-read.
pub const SCHEMA_VERSION: i64 = 1;

const DDL_V1: &str = r#"
-- Layer 1: the log. Append-only. Never updated.
CREATE TABLE IF NOT EXISTS events (
  seq         INTEGER PRIMARY KEY AUTOINCREMENT,  -- local ingest order
  ntfy_id     TEXT NOT NULL UNIQUE,               -- ntfy's id: the total-order key
  ntfy_time   INTEGER NOT NULL,
  message_id  TEXT NOT NULL,
  type        TEXT NOT NULL,
  subject_id  TEXT,        -- questionId | reviewId | notificationId | forMessageId
  payload     TEXT NOT NULL  -- full decrypted JSON, verbatim
);
CREATE INDEX IF NOT EXISTS idx_events_subject ON events(subject_id);

-- Layer 2: projections. Derived. Droppable and rebuildable at any time.
CREATE TABLE IF NOT EXISTS messages (
  message_id   TEXT PRIMARY KEY,
  type         TEXT NOT NULL,
  session_key  TEXT,          -- NULL until sender_identity joins
  project_key  TEXT,
  created_at   INTEGER NOT NULL,
  status       TEXT NOT NULL, -- folded, §7.2
  verdict      TEXT,
  responder    TEXT,
  responded_at INTEGER,
  title        TEXT NOT NULL,
  context      TEXT,
  repo_name    TEXT,
  repo_branch  TEXT
);
CREATE TABLE IF NOT EXISTS sessions (
  session_key TEXT PRIMARY KEY,
  project_key TEXT,
  label       TEXT,
  first_seen  INTEGER,
  last_seen   INTEGER
);
CREATE TABLE IF NOT EXISTS projects (
  project_key TEXT PRIMARY KEY,
  name        TEXT,
  last_seen   INTEGER
);

-- Durable, and deliberately not a projection: see the module comment.
CREATE TABLE IF NOT EXISTS bodies (
  content_hash TEXT PRIMARY KEY,
  bytes        BLOB
);
CREATE TABLE IF NOT EXISTS summaries (
  message_id  TEXT PRIMARY KEY,
  summary     TEXT,
  model       TEXT,
  created_at  INTEGER
);
"#;

/// Bring `conn` up to [`SCHEMA_VERSION`], doing nothing when it is already there.
pub fn migrate(conn: &Connection) -> Result<()> {
    let current: i64 = conn.query_row("PRAGMA user_version", [], |row| row.get(0))?;
    if current >= SCHEMA_VERSION {
        return Ok(());
    }

    conn.execute_batch(DDL_V1)?;
    // No parameter binding on a PRAGMA, hence the format. SCHEMA_VERSION is a
    // compile-time constant, so there is nothing here for a caller to inject.
    conn.execute_batch(&format!("PRAGMA user_version = {SCHEMA_VERSION}"))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn migrating_twice_is_a_no_op() {
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();
        migrate(&conn).unwrap();

        let version: i64 = conn.query_row("PRAGMA user_version", [], |r| r.get(0)).unwrap();
        assert_eq!(version, SCHEMA_VERSION);
    }

    #[test]
    fn every_table_the_spec_names_exists() {
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();

        for table in ["events", "messages", "sessions", "projects", "bodies", "summaries"] {
            let found: i64 = conn
                .query_row(
                    "SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?1",
                    [table],
                    |r| r.get(0),
                )
                .unwrap();
            assert_eq!(found, 1, "{table} must exist");
        }

        let index: i64 = conn
            .query_row(
                "SELECT count(*) FROM sqlite_master WHERE type='index' AND name='idx_events_subject'",
                [],
                |r| r.get(0),
            )
            .unwrap();
        assert_eq!(index, 1, "idx_events_subject must exist");
    }

    #[test]
    fn dropping_the_projections_leaves_the_log_intact() {
        // The recovery path the invariant promises. If this ever needs more
        // than a DROP and a rebuild, something authoritative leaked into a
        // projection.
        let conn = Connection::open_in_memory().unwrap();
        migrate(&conn).unwrap();
        conn.execute(
            "INSERT INTO events (ntfy_id, ntfy_time, message_id, type, subject_id, payload)
             VALUES ('n-1', 1, 'm-1', 'question', 'm-1', '{}')",
            [],
        )
        .unwrap();

        conn.execute_batch("DROP TABLE messages; DROP TABLE sessions; DROP TABLE projects;")
            .unwrap();

        let events: i64 = conn.query_row("SELECT count(*) FROM events", [], |r| r.get(0)).unwrap();
        assert_eq!(events, 1);
    }
}
